### ISSUE TITLE
Question: RunSynchronously possible?

### ISSUE THREAD

**Issue by JOEHRHARDT** [Astn/JSON-RPC.NET#101]
Is it possible to carry out JsonRpcProcessor.Process in parent thread? Like with Task.RunSynchronously.

**Comment by Astn** [comment]
Not without creating another variation of the Process function.
https://github.com/Astn/JSON-RPC.NET/blob/master/Json-Rpc/JsonRpcProcessor.cs#L34

It may still need to run inside of a Task though.

Feel free to submit a pull request.

**Comment by Astn** [comment]
Now possible https://github.com/Astn/JSON-RPC.NET/blob/82d23f1259be9e931cbe6dcff60df8330d49b471/Json-Rpc/JsonRpcProcessor.cs#L49
