### ISSUE TITLE
Ablity to handle extra parameters in the JSON-RPC method

### ISSUE THREAD

**Issue by midmohan** [Astn/JSON-RPC.NET#111]
Currently when extra parameters are present inside the parameters, the library throws ,

"error":{"code":-32602,"message":"Invalid params","data":"Expecting 4 parameters, and received 5"},

It would be good to have the ability, to ignore the extra params and call the method with the supported params.

**Comment by j-schuma** [comment]
You can just define a method signature with 5 param and define a default for the optional one.

**Comment by pedrolcl** [comment]
@j-schuma optional parameters is not what this feature request is about. But I don't thing it is a good idea, either.

**Comment by Astn** [comment]
I'm going to close this as @j-schuma provides a good work around for this type of issue.
