### ISSUE TITLE
How to generate the JSON text with named parameters?

### ISSUE THREAD

**Issue by jdengitw** [Astn/JSON-RPC.NET#112]
Hello,
My JSON text is with positional parameters now, I'm going to change it to named parameters. Is there a function I can call or I need to implement it by myself?
Thanks.

example:
What I have now.
![image](https://user-images.githubusercontent.com/40221435/78342709-433beb80-75cc-11ea-8ece-aeebefaf33a9.png)
What I want.
![image](https://user-images.githubusercontent.com/40221435/78342803-6ebed600-75cc-11ea-85cd-7156b34f7bfd.png)

**Comment by Astn** [comment]
There is nothing extra you should need to do. Just try switching one of your calls to use named parameters and it should work. Both calling styles should work at the same time.

Any code in your client you need to write your self. 

I don't understand this part of your question:
> Is there a function I can call or I need to implement it by myself?

A function for what, or implement what your self?

**Comment by jdengitw** [comment]
Thank you for the quick reply.
I mean do I need to modify the class JsonRequest?

**Comment by Astn** [comment]
It's automatic. 
You don't need to do anything different on the server. Just on the client send the request using the object style instead of the array style.

**Comment by jdengitw** [comment]
Thanks very much.
