### ISSUE TITLE
Small update?

### ISSUE THREAD

**Issue by peder2key** [Astn/JSON-RPC.NET#113]
Hello!

Would it be possible to update the nuget? It's using a very old version of newtonsoft.json

Best regards

**Comment by Astn** [comment]
👍 
Ya, It has been a while. I'll run it through the ringer and get a new package out there.

**Comment by Astn** [comment]
@peder2key I just pushed out a new version ![NuGet Badge](https://buildstats.info/nuget/AustinHarris.JsonRpc)

**Comment by peder2key** [comment]
Nice work! :)
