### ISSUE TITLE
Add async/await support instead of IAsyncResult

### ISSUE THREAD

**Issue by DenisBalan** [Astn/JSON-RPC.NET#122]
Currently self-hosted wiki documentation states that `JsonRpcStateAsync` should be used.
Which inherits from IAsyncResult, and other classes as well have old asynchronous model classes and properties (`WaitHandle`,  `AsyncState`, `IsCompleted` etc).

This issue is to propose to migrate to newer model of async programming model.

**Comment by Astn** [comment]
Great catch @DenisBalan, the wiki is out dated.

Using one of the Process functions that returns a Task<string> is the way to go!
https://github.com/Astn/JSON-RPC.NET/blob/ee15bdb9827fb00f920866e2970d2e8d0ad24111/Json-Rpc/JsonRpcProcessor.cs#L30

**Comment by Astn** [comment]
I updated the example on https://github.com/Astn/JSON-RPC.NET/wiki/Getting-Started-(Console)
If there is another place, feel free to update it. The wiki is open.
