### ISSUE TITLE
Optional parameters parse bug

### ISSUE THREAD

**Issue by LonerKO** [Astn/JSON-RPC.NET#124]
I have method with 4 optional parameters
`public UpdateDomainView UpdateDomain(string domain, ApiRegistrantEntity s_registrant = null, ApiRegistrantContractEntity contract_info = null, IEnumerable<ApiDsRecord> dsRecords = null, Dictionary<string, string> s_ns = null) {}`
When i try to set only  second, third or fourth optional parameter => all optional parameters are null. 
If i set first optional and third optional only first optional parametel will be not null but others are NULL
Why?

**Comment by Astn** [comment]
If this is still and issue, and you can provide a unit test of the problem, I'm happy to take a look.
