### ISSUE TITLE
Configurable JSON serialization/deserialization

### ISSUE THREAD

**Issue by hovi** [Astn/JSON-RPC.NET#127]
Is there way to configure the serializer? I see this library is using newtonjson.
In my case I'd like to set `NullValueHandling = NullValueHandling.Ignore` for data response objects.

**Comment by Astn** [comment]
Off the top of my head, I think anything you annotate on your own models works. 
There may be a serializer settings you can access. If now then we should add one.

**Comment by Astn** [comment]
I just looked, and it's not exposed yet in the main branch.

**Comment by hovi** [comment]
If you give me a lead, I might try to make a PR. C# is not my strong language though.

**Comment by Astn** [comment]
@hovi Sure thing.
The main place to start would be in JsonRpcProcessor.cs 
Fuctions `Process` wrap calls to `ProcessInternal`. Those would be where you would add the JsonSerializerSettings optional parameter.

![image](https://user-images.githubusercontent.com/6857743/132922469-b4bc843a-60f5-44e7-a852-4ed41095ff0e.png)


Then there are a handfull of places the method could return if there are errors, so any call to `JsonConvert.SerializeObject` would be where the `JsonSerializerSettings` get passed.

![image](https://user-images.githubusercontent.com/6857743/132922358-0b5c6533-aba6-464f-b181-50e0ab446a18.png)

**Comment by Astn** [comment]
This is published it to nuget as of version 1.2.3 @ https://github.com/Astn/JSON-RPC.NET/commit/177be604e532fe2c1e11fec9d4c8447138f7f741
