### ISSUE TITLE
JsonRpcProcessor ignores JsonSerializerSettings on response serialization

### ISSUE THREAD

**Issue by delinea530** [Astn/JSON-RPC.NET#129]
I think there is a bug in JsonRpcProcessor.ProcessSync() method since the serialization of the response of a request ignores completely the `settings` (a `JsonSerializerSettings` instance) argument.

https://github.com/Astn/JSON-RPC.NET/blob/177be604e532fe2c1e11fec9d4c8447138f7f741/Json-Rpc/JsonRpcProcessor.cs#L139-L146

**Comment by babang1da** [comment]
++++

**Comment by babang1da** [comment]
FIX
https://www.newtonsoft.com/json/help/html/DefaultSettings.htm

**Comment by gerardo-contijoch** [comment]
> FIX https://www.newtonsoft.com/json/help/html/DefaultSettings.htm

The problem is not with the default settings, the problem is that the code that was referenced in this issue ignores the argument `settings` of `JsonRpcProcessor.ProcessSync(...)`.

**Comment by Astn** [comment]
Merged
