### ISSUE TITLE
Threading consideration/Main UI Thread

### ISSUE THREAD

**Issue by codenotes** [Astn/JSON-RPC.NET#39]
Great library, would be ideal if documentation or sample application could show optimal method of calling into the main UI thread.  The RPC mechanism exists on a separate thread, and so the RPC function is unable to get or set any aspect of the UI.  Although in most cases one would use this library with a console or asp app, using with wpf isn't uncommon and that is where it would be very useful

**Comment by raistlinthewiz** [comment]
Invoke the call async and update the UI once the call is done?

**Comment by codenotes** [comment]
Really, not so much about updating the  UI as it is retrieving data from the UI thread.  In my case, the UI has a bing map control with placeholders on it...I am trying to get the coordinates of these from the RPC call.  
I am reading up on how to do this, has to do with Dispatcher and such, the following works when invoked from the RPC method:

    Application.Current.Dispatcher.Invoke
                (new Action(   () => mainwindow.somefunc()  )  );

Although this doesn't let me return anything.  Looking for another method, maybe Func<> will work, so that I can get a return value.  .NET is not my primary language/environment, so reading up on Task, async and all that.  Will post if/when I figure it out.

**Comment by Astn** [comment]
This does not appear to be an issue with this library.
