### ISSUE TITLE
Make DLL's available for download

### ISSUE THREAD

**Issue by 4nd3250n** [Astn/JSON-RPC.NET#46]
Please please please make dll's availbale for direct download.
Nuget just doesn't work. Each time I spend hours trying to make it work, IT JUST DOESN'T.
It would save so much time if i could just download and reference dll files.

**Comment by Astn** [comment]
A .nupkg file is just a zip file with a different extension.
You can manually download any of released versions from here: https://www.nuget.org/packages/AustinHarris.JsonRpc/ using the download link on the left side. Then you just need to extract the .nupkg file with your favorite archive utility. You may have to rename to .zip depending on the archive utility you are using.
Hope that helps.
