### ISSUE TITLE
Question about RPC service on client side

### ISSUE THREAD

**Issue by NickAb** [Astn/JSON-RPC.NET#48]
Hello,

Can this package be used when we have reverse server-client structure.

In my case client will connect to web socket server and then server should be able to make remote calls to client (which will be implemented on client).

**Comment by raistlinthewiz** [comment]
why not? your "client" just acts as a server in your case :)

**Comment by NickAb** [comment]
Yeah, thanks.

One more question.
Is there a way to generate C# client bindings, so that instead of:
```cs
var client = new JsonRpcClient(uri);
var request = client.Invoke<object>("Echo", "hi", Scheduler.ThreadPool);
...
```
we could use something like:
```cs
IServiceProvider provider = new JsonOverHttp(url);
var client = JsonRpcClient<ISomeRpc>(provider);
var request = client.Echo("hi");
...
```
So that we have the comfort of IDE autocompletion and refactoring.

**Comment by xmedeko** [comment]
Interface `ISomeRpc` is nice when the server and client are written in C#, only. But is useless for multilingual projects. Using old good `const`
````
private const string ECHO = "Echo";
````
makes a job for IDE autocompletion, too.
