### ISSUE TITLE
Bidirectional communication example

### ISSUE THREAD

**Issue by xmedeko** [Astn/JSON-RPC.NET#49]
Please, make a bidirectional Console or Socket example on Wiki. Thanks.

**Comment by Astn** [comment]
Are you referring to the server having the ability to "push" a message to the client?

**Comment by xmedeko** [comment]
Yep, I mean the full, asynchronous, bidirectional JSON-RPC over TCP example. IMO one of the main reason to choose the bare TCP only over the HTTP is when the project needs the bidirectional communication.

I have not any previous experience with .NET and Socket coding. After some days of coding I think I has a kind of limited solution. But we have decided to abandon it because of the complexity, try the HTTP instead and simulate the "server - client" push by a client polling in our project.

**Comment by Astn** [comment]
This would be a complicated example, and might be considered outside the scope of json-rpc. You would need a specific implementation of a json-rpc service to get this type of thing to work, then you would be running it client side, and server side. I'd be more then happy to review a submission to the wiki, but I don't believe that I have the time to write up this type of example.
