### ISSUE TITLE
Example please

### ISSUE THREAD

**Issue by Buzzroid** [Astn/JSON-RPC.NET#53]
Could you please make some example programs showing your greate framework?
TestServer_Console is not enough to understand to a newbie like me.
Thanks.

**Comment by Astn** [comment]
Have you looked through the test project?
https://github.com/Astn/JSON-RPC.NET/tree/master/AustinHarris.JsonRpcTestN
Or the benchmark test project?
https://github.com/Astn/JSON-RPC.NET/tree/master/TestServer_Console

Would you like to grab some content out of either of those and add another page to the wiki?
