### ISSUE TITLE
Incorrect Newtonsoft.JSON framework version installed when grabbing Nuget package in VS2013 Express for desktop

### ISSUE THREAD

**Issue by jbreens** [Astn/JSON-RPC.NET#65]
Hey all, 

I've been using JSON-RPC.NET for the last few years. I recently updated my 2 year old version of the framework (downloaded manually back in the day) and updated to the latest using VS's built in Nuget Package manager. As part of the update, the NewtonSoft JSON framework is also installed as a dependency. 

When next building my application, I got this exception: 
`InnerException {"Could not load file or assembly 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.":"Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"}    System.Exception {System.IO.FileNotFoundException}`

The version installed with the NuGet package was 6.0.0.5. I downloaded the latest Nuget version of NewtonSoft JSON and all was well, I wrote this off as fluke. 

However, I just today started a fresh Solution, and after installing the Nuget package, I got the same issue again. Could the dependencies on the Package be incorrect?

**Comment by Astn** [comment]
Sure could, I'll have to take a look. Thanks for reporting the issue.
