### ISSUE TITLE
StackOverflowException with LinkedList

### ISSUE THREAD

**Issue by SaikoProj** [Astn/JSON-RPC.NET#67]
I have simple data class.
```
public class Test
{
	private Question currentQuestion;
	public event Action<Question> OnNext;
	public event Action OnFinished;
	public LinkedList<Question> Questions { get; }
}
```
When i create my service with method 
```
[JsonRpcMethod]
		public Test GetTest(int questionsCount)
		{
			....
		}
```
VS lock and after some times throw StackOverflowException
If i change Questions type to List<> exception not throw

**Comment by Astn** [comment]
Possibly fixed with https://github.com/Astn/JSON-RPC.NET/commit/b9f435a38e051550aea12da79b3857740d3c8c04
Can you test?

**Comment by SaikoProj** [comment]
Possibly nuget package is outdate
