### ISSUE TITLE
System.TypeInitializationException

### ISSUE THREAD

**Issue by jbreens** [Astn/JSON-RPC.NET#69]
Hi,

Recently started new project, first time running JSON-RPC service, (fresh dev environment) I get a System.TypeInitializationException when calling JsonRpcService base constructor. Specifically at bindservice. See attached screenshot. 

JB
![capture](https://cloud.githubusercontent.com/assets/6030054/19883531/32a6390a-a015-11e6-90cf-a673201b4fe3.PNG)

**Comment by jbreens** [comment]
Hey guys, just tried to uninstall and re-install the nuget packets. Can confirm I get this exception when calling the base constructor even after re-installation. 

I manually grabbed the nuget packets (which show the same version number) from an older project, and now it's fine.

**Comment by Astn** [comment]
Thanks for reporting the issue! Hopefully just a Nuget issue. I'll check it out.

**Comment by Astn** [comment]
Which framework version is your project?

**Comment by Astn** [comment]
I've just tested this on 3 new projects 4.0, 4.5, 4.6.1, and the nugget I published last night does not have this issue. So #74 did fix it.
