### ISSUE TITLE
Can not comunicate when separate from message sender and message receiver.

### ISSUE THREAD

**Issue by KingSea168** [Astn/JSON-RPC.NET#70]
Hi all,
We find a problem about comunication and need to solve. 

First at all, the html page(message sender) and winform application(message receiver) can comunication at same webbroswer.(the winform application embedded a geckoWebBrowser1)
`geckoWebBrowser1.AddMessageEventListener("JsonRpcBridge", this.JsonRpcBridge);
 geckoWebBrowser1.Navigate(System.IO.Path.Combine(Application.StartupPath, "www", "index.html"));`

But, if separate them,the winform application run as a message receiver to listen html page's message,while the html page run as a message sender at firefox or chrome browser. Unfortunately, the winform application can not receive any message from html page. we don't know is it the html page haven't send message or the winform application can not recevie message.
`geckoWebBrowser1.AddMessageEventListener("JsonRpcBridge", this.JsonRpcBridge);
 //geckoWebBrowser1.Navigate(System.IO.Path.Combine(Application.StartupPath, "www", "index.html"));
// run this url(System.IO.Path.Combine(Application.StartupPath, "www", "index.html")) at firefox or chrome broswer`

Please help us solve the problem, we will thank you a  lot.

**Comment by Astn** [comment]
How are you invoking the JsonRpcProccessor?
You can also register a global event handler and log is happening from the processor's perspective. See: https://github.com/Astn/JSON-RPC.NET/wiki/Logging-or-Authentication-Using-Context

**Comment by Astn** [comment]
Closing as there is not enough information reported to reproduce the issue.

**Comment by KingSea168** [comment]
@Astn Thx Astn, I will have a try to solve.
