### ISSUE TITLE
Not working in C# RESTFul API 2

### ISSUE THREAD

**Issue by minakshibh** [Astn/JSON-RPC.NET#96]
I have tried alot with different stuff but I am unable to send request and response to the methods I created. Can you please tell me where I am doing wrong in this?

In a Class on Web API project I have written following code:

```
using AustinHarris.JsonRpc;
public class GTECService : JsonRpcService
 {
        [JsonRpcMethod]
        public string TransactionStatus(string message)
        {
            return message;
        }
    }
```

In my global.aspx, following is code written:

```
public class WebApiApplication : System.Web.HttpApplication
    {
        private GTECService service;
       protected void Application_Start()
        {
            var container = new Container();
            container.Options.DefaultScopedLifestyle = new AsyncScopedLifestyle();
            container.Register<ISchedulerBusiness, SchedulerBusiness>(Lifestyle.Scoped);    
            container.RegisterWebApiControllers(GlobalConfiguration.Configuration);
            container.Verify();
            AreaRegistration.RegisterAllAreas();
            GlobalConfiguration.Configure(WebApiConfig.Register);
             service = new GTECService();
        }
}
```

And 
In web config I have added this stuff:

```
. . . . . . . . . . . . . . .
 <handlers>
      <remove name="ExtensionlessUrlHandler-Integrated-4.0" />
      <remove name="OPTIONSVerbHandler" />
      <remove name="TRACEVerbHandler" />
      <add name="ExtensionlessUrlHandler-Integrated-4.0" path="*." verb="*" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0" />
      <add name="jsonrpc" type="AustinHarris.JsonRpc.Handlers.AspNet.JsonRpcHandler" verb="*" path="*.rpc" />
    </handlers>
    <validation validateIntegratedModeConfiguration="false" />
  </system.webServer>
```

and I am testing in Postman using **Postman Interceptor** as following:

![image](https://user-images.githubusercontent.com/12507440/43776075-64ed0814-9a6c-11e8-810e-e15447d25729.png)

with body as follwing:

![image](https://user-images.githubusercontent.com/12507440/43776160-9ddbd880-9a6c-11e8-8b99-a7e38429c930.png)

Further 
I am getting above issue with all the tries, I was testing the same over localhost then I uploaded on server but no luck!!

Can anyone help me out. I am worried about this from last Friday. Any help would be appreciated.

**Comment by Astn** [comment]
I'm sorry it's not working for you.

I did notice that in your config that you are telling it to bind to any URL that has a path that ends in .rpc. So a path that I would expect it to work against would be something like http://200.124.153.227/foobar.rpc though in your postman screen shots you are using a url that does _not_ end in .rpc
`<add name="jsonrpc" type="AustinHarris.JsonRpc.Handlers.AspNet.JsonRpcHandler" verb="*" path="*.rpc" />`

**Comment by gaganpreetscrear** [comment]
Hi 
I have sort it out!

One issue I am left with and searching from last 3-4 days.

I have a method where I need to return Array like:
       `{"jsonrpc":"2.0","result":"{"EUR":"0","XBT":"TX000"}","id":"1"}` this

But When I tried to return something with **json data** or **else**:

I got **500 - Internal Server error**

Here is my code:

```
        [JsonRpcMethod]
        public object getBalances(string userUuid)
        {
            JObject json = new JObject();
            json.Add("EUR", 0);
            json.Add("XBT", 0);
            
            return json;
         }
```

PS: It works perfect if I return only string.

**Comment by minakshibh** [comment]
Hi Austin,

Same issue as @gaganpreetscrear is facing. 
@gaganpreetscrear did you get solution for that ?

If anyone knows please give solution for this!

**Comment by Astn** [comment]
@gaganpreetscrear Have you tried making your method return a JObject instead of an Object?

**Comment by Astn** [comment]
Can you open a pull request with an example project that demonstrates this issue?
