### ISSUE TITLE
Response Content Type is text/html

### ISSUE THREAD

**Issue by DMEvans** [Astn/JSON-RPC.NET#97]
All HTTP responses from the JSON-RPC handler appear to have the Content-Type of text/html

According to the specification for [JSON-RPC over HTTP](https://www.jsonrpc.org/historical/json-rpc-over-http.html) the request and response Content-Type should be one of the following:

"application/json-rpc" - **preferred**
"application/json"
"application/jsonrequest"

**Comment by Astn** [comment]
Great find!
