### ISSUE TITLE
Received parameter in client is not equal to that sent in server

### ISSUE THREAD

**Issue by jdengitw** [Astn/JSON-RPC.NET#99]
If I send a server function continually, sometimes the client will lose one. Then when I send it one more time, the client will get the last losed one.

Is this a potential issue?

**Comment by Astn** [comment]
Any chance you could post some code showing what issue you are experiencing?

**Comment by jdengitw** [comment]
I think I made a mistake in my own code. 
I added 2 server functions with the same name but different number of parameters, these 2 functions are  triggered at the same time. I only handled one function in my client code. It works well after deleting one function in server.
